config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show]

  resource :session, only: [:new, :create, :destroy]

  resources :goals

  resources :comments, only: [:create, :destroy]

  root "sessions#new"

  patch "goals/:id/mark_as_complete", to: 'goals#mark_as_complete'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :owner, :body, presence: true

  belongs_to :commentable, polymorphic: true

  belongs_to :owner,
    foreign_key: :user_id,
    class_name: :User
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :user, :description, presence: true
  validates :status, inclusion: { in: ["COMPLETE", "INCOMPLETE"] }
  validates :private, inclusion: { in: ["PRIVATE", "PUBLIC"] }


  belongs_to :user

  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :owned_comments,
    foreign_key: :user_id,
    class_name: :Comment

  has_many :comments, as: :commentable

  has_many :goals

  def self.find_by_credentials(username, pw)
    user = User.find_by(username: username)
    user && user.is_password?(pw) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(128)
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in(user)
    session[:session_token] = user.session_token
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    unless @comment.save
      flash[:errors] = @comment.errors.full_messages
    end
    @comment.commentable_type == "User" ? redirect_to(user_url(@comment.commentable_id)) : redirect_to(goal_url(@comment.commentable_id))
  end

  def destroy
    @comment = Comment.find(params[:id])
    id = @comment.commentable_id
    type = @comment.commentable_type
    @comment.destroy
    type == "User" ? redirect_to(user_url(id)) : redirect_to(goal_url(id))
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :same_author, only: [:update, :edit, :destroy]
  before_action :see_private, only: [:show]

  def index
    @goals = Goal.where(private: "PUBLIC").to_a
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def new

  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    user = @goal.user
    @goal.destroy
    redirect_to user_url(user)
  end

  def mark_as_complete
    @goal = Goal.find(params[:id])
    @goal.status = "COMPLETE"
    @goal.updated_at = Time.now
    @goal.save
    redirect_to user_url(@goal.user)
  end

  private

  def see_private
    @goal = Goal.find(params[:id])
    redirect_to goals_url unless @goal.private == "PUBLIC" || current_user == @goal.user
  end

  def goal_params
    params.require(:goal).permit(:description, :status, :private)
  end

  def same_author
    @goal = Goal.find(params[:id])
    redirect_to goals_url unless current_user.id == @goal.user_id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])

    if @user
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid login"]
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/index.html.erb
<h1>Goals Index</h1>

<ul>
  <% @goals.each do |goal| %>

    <li>
      <%= link_to goal.description, goal_url(goal) %> by <%= link_to goal.user.username, user_url(goal.user) %>
    </li>

  <% end %>
</ul>

app/views/goals/show.html.erb
<h1>Goal Details</h1>

Author: <%= @goal.user.username %>
<%= @goal.description %>
Goal made: <%= @goal.created_at %>
Goal completed: <%= @goal.updated_at if @goal.status == "COMPLETE" %>
<%= @goal.status %>

<%= link_to "Edit Goal", edit_goal_url(@goal) %>
<%= button_to "Delete Goal", goal_url(@goal), method: :delete %>

<%= link_to "All Goals", goals_url %>

<h2>Comments</h2>

<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="comment[commentable_type]" value="<%= Goal %>">
  <input type="hidden" name="comment[commentable_id]" value="<%= @goal.id %>">

  <label for="">Comment:<textarea name="comment[body]" rows="8" cols="50"></textarea></label>

  <input type="submit" name="" value="Add Comment">
</form>

<ul>
  <% @goal.comments.each do |comment| %>
    <li>
      <h6><%= comment.owner %></h6><br>
      Posted at:<%= comment.created_at %><br>
      <%= comment.body %>
      <%= button_to "Remove Comment", comment_url(comment), method: :delete if current_user == comment.owner %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuccessApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <% if current_user %>
    <%= current_user.username %>
    <%= button_to 'Sign Out', session_url, method: :delete %>
  <% else %>
    <%= link_to 'Sign In', new_session_url %>
    <%= link_to 'Register', new_user_url %>
  <% end %>
</header>
<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Goals</h1>

<%= link_to "Add Goal", new_goal_url if current_user == @user %>

<ul>
  <% @user.goals.each do |goal| %>
    <% if goal.status == "INCOMPLETE" && (goal.user == current_user || goal.private == "PUBLIC")%>
      <li><%= goal.description %>
        <%= button_to "Mark as Complete", "/goals/#{goal.id}/mark_as_complete", method: :patch if current_user == @user %>
        <%= button_to "Delete Goal", goal_url(goal), method: :delete if current_user == @user %>
      </li>
    <% end %>
  <% end %>
</ul>

<h2>Completed Goals</h2>

<ul>
  <% @user.goals.each do |goal| %>
    <% if goal.status == "COMPLETE" && (goal.user == current_user || goal.private == "PUBLIC")%>
      <li>
        <%= goal.description %>
        <%= button_to "Delete Goal", goal_url(goal), method: :delete if current_user == @user %>
      </li>
    <% end %>
  <% end %>
</ul>


<h2>Comments</h2>

<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="comment[commentable_type]" value="<%= User %>">
  <input type="hidden" name="comment[commentable_id]" value="<%= @user.id %>">

  <label for="">Comment:<textarea name="comment[body]" rows="8" cols="50"></textarea></label>

  <input type="submit" name="" value="Add Comment">
</form>

<ul>
  <% @user.comments.each do |comment| %>
    <li>
      <h6><%= comment.owner %></h6><br>
      Posted at:<%= comment.created_at %><br>
      <%= comment.body %>
      <%= button_to "Remove Comment", comment_url(comment), method: :delete if current_user == comment.owner %>
    </li>
  <% end %>
</ul>